### ISSUE TITLE
Larger Variety of Planet textures

### ISSUE THREAD

**Issue by ChaseBENNC9** [BIT-Studio-3/Space-Rescue#109]
As Mentioned by the product owner, The planets should have more unique visuals with a larger variety of planet types. This will also help them be more identifiable when using the Planet UI indications

**Comment by PBWiseman** [comment]
Just a note that this issue is for planet textures. We are sticking with the plain spherical planet.

**Comment by PBWiseman** [comment]
Reopening this as I have added more planets for more variety.
