### ISSUE TITLE
Title Screen Rework

### ISSUE THREAD

**Issue by erokasyuart** [BIT-Studio-3/Space-Rescue#114]
As a product owner, I want the title screen to be text rather than buttons so the menu can have a modern design.
As a user, I want the title screen UI to be less cluttered and minimalist to make the menu more usable and direct.

Some inspiration images:
![image](https://github.com/BIT-Studio-3/Space-Rescue/assets/100744555/189069b8-6541-447c-9883-649428c4d4c1)
![image](https://github.com/BIT-Studio-3/Space-Rescue/assets/100744555/b5a24897-dfba-48b9-9a17-125d95b3f5b9)
![image](https://github.com/BIT-Studio-3/Space-Rescue/assets/100744555/96c3efbf-159f-42b1-9a90-18c3b1b1e2bd)
![image](https://github.com/BIT-Studio-3/Space-Rescue/assets/100744555/862fc38e-1f47-4115-b3df-5c9f44c93cf3)

It was also suggested that the planet background should be the black hole with the ship floating past.

**Comment by erokasyuart** [comment]
### 7 Title screen mockups

- The circles in the background represent the black hole which I think is a core element of the game so should get a placement in the title, rather than a planet because there are many of them and none have higher importance over the other.
- Adding onto the black hole background, using Adon's suggestion, I drew inspiration from the Dune and Alien Isolation planets being off-centred. 
- Some images use a divider, which would be especially needed for the usability of the title screen to help differentiate what is clickable buttons and what is the title name for the user, especially if the title uses smaller text.
- I use minimal text for a minimalist design. Settings and keybinds could be merged into one options menu that uses tabs for different sections, just to clean up the look of the title screen.
- Something to consider is the use of balance between larger text and the black hole. In the design hierarchy, the larger text draws the attention of the user, but also anything that sits left of the screen where the user's eyes go first.
- I also want to use a mixture of GUI and the 3D assets which is why I mention the black hole, rather than full GUI.
- Adding onto the above statement, I had the funny idea to occasionally have animals floating past to reference that one bug where animals migrated from the planet scene to the minigame scene and their gravity would make them float around.

![Drawing](https://github.com/BIT-Studio-3/Space-Rescue/assets/100744555/ebc1e595-9634-49cd-9f34-bd1df5c74627)
![Drawing (1)](https://github.com/BIT-Studio-3/Space-Rescue/assets/100744555/bf854589-9702-4718-802d-5e4d93d4e714)
![Drawing (2)](https://github.com/BIT-Studio-3/Space-Rescue/assets/100744555/9cd5fb25-b5a5-4e4b-8410-ffc4822145e6)
![Drawing (3)](https://github.com/BIT-Studio-3/Space-Rescue/assets/100744555/d06804f4-8e3a-4562-ab12-263033ddbe70)
![Drawing (4)](https://github.com/BIT-Studio-3/Space-Rescue/assets/100744555/3355eca7-9fc0-44a1-bd8b-ad4825c42b8e)
![Drawing (5)](https://github.com/BIT-Studio-3/Space-Rescue/assets/100744555/980903f2-78d1-43a2-9775-2b16f97001a9)
![Drawing (6)](https://github.com/BIT-Studio-3/Space-Rescue/assets/100744555/e82c25b9-e6ca-49e2-ac28-228d522dc328)

**Comment by ChaseBENNC9** [comment]
Liking your ideas so far, 
Personally I like concepts 3 , 4 and 5 the most. Like the idea of keeping the menu minimalistic and using the black hole as a background graphic.

**Comment by PBWiseman** [comment]
I love the concepts. I think 1 looks really good in wireframe but the black hole being there might make it awkward to read.
4 and 5 are my favorites. I'd have to see how the larger title text looks with the font we are using? I really like the title with dividing line though. Looks very clean. Not sure why I don't like top right menu as much. I think it just doesn't visually flow as well as title menus on the bottom half of the screen.

**Comment by PBWiseman** [comment]
I think the animals could be funny. Maybe as a very rare easter egg later 😆
