### ISSUE TITLE
Updated Pause Menu

### ISSUE THREAD

**Issue by erokasyuart** [BIT-Studio-3/Space-Rescue#129]
- New design
- Fix key binds
- Moving the settings menu back to a different scene so it can be overlayed onto the gameplay

As a player, I want an updated sleek GUI for the pause menu so it will match the title screen GUI
As a player, I want the key bind menu to go to the title screen key bind menu because it makes more sense to go to the same menu I've already seen.

**Comment by erokasyuart** [comment]
- Moving the settings menu back to a different scene so it can be overlayed onto the gameplay

**Comment by erokasyuart** [comment]
![Drawing sketchpad](https://github.com/BIT-Studio-3/Space-Rescue/assets/100744555/d8c3d582-12a6-467c-aa59-2a0ffdd5010b)
![Drawing sketchpad (1)](https://github.com/BIT-Studio-3/Space-Rescue/assets/100744555/7301b926-84a1-4efd-86d2-8ad0e1065be1)
![Drawing sketchpad (2)](https://github.com/BIT-Studio-3/Space-Rescue/assets/100744555/42d9893c-9820-42ac-8cca-3de408aa9cd8)
![Drawing sketchpad (3)](https://github.com/BIT-Studio-3/Space-Rescue/assets/100744555/c9da8eff-dcb2-40d5-b780-630dd22c5d6e)
![Drawing sketchpad (4)](https://github.com/BIT-Studio-3/Space-Rescue/assets/100744555/570fa610-835e-4323-b8dd-31cb52599f80)
![Drawing sketchpad (5)](https://github.com/BIT-Studio-3/Space-Rescue/assets/100744555/f45ca017-2f7e-4651-b04c-c0b9783e1b6d)

- This will not be a separate scene. This will overlay the gameplay.
- Background will have a dark filter over it to add some contrast between the text and the game.
- I added a border just to fill in some space but please let me know if there are some features in any of these you think should be tweaked

**Comment by PBWiseman** [comment]
3 and then 1 are my favorites personally. I like the look of the larger continue

**Comment by ChaseBENNC9** [comment]
I agree. I like concepts 1 and 3 the most.

**Comment by erokasyuart** [comment]
https://www.google.com/search?q=rounded+corners+unity&rlz=1C1GCEB_enNZ1047NZ1047&oq=round+border+unity&aqs=chrome.1.69i57j0i10i22i30j0i10i15i22i30j0i22i30.5869j0j7&sourceid=chrome&ie=UTF-8#kpvalbx=_yanRZJ2YAcqa2roPwOKUiAo_47

I can use sprites!
