### ISSUE TITLE
Title Screen Resolution

### ISSUE THREAD

**Issue by erokasyuart** [BIT-Studio-3/Space-Rescue#130]
As a player with uncommon aspect ratio sized monitor, I want all the GUI to be conventional to all screen sizes.

The GUI for the title screen canvas' uses 'scale with screen size' under 'canvas scaler' which fixes the GUI resizing for SOME of the aspect ratios but not all- only free aspect and 16:10.

**Comment by PBWiseman** [comment]
16:10 scaling for menus currently broken
