### ISSUE TITLE
Update End Game Screen

### ISSUE THREAD

**Issue by PBWiseman** [BIT-Studio-3/Space-Rescue#133]
**User Story**
As a user, I want all the menus to look similar, so there is visual consistency

Current end game screen is very outdated and should be updated to the new visual style of the main menu.

**Comment by ChaseBENNC9** [comment]
Also will solve #134

**Comment by ChaseBENNC9** [comment]
Concepts
![image](https://github.com/BIT-Studio-3/Space-Rescue/assets/104808214/339f6b1a-47a3-48ed-83db-75f9d9aeaaa6)
![image](https://github.com/BIT-Studio-3/Space-Rescue/assets/104808214/e567feef-9423-4531-9630-fe304195cc9f)
![image](https://github.com/BIT-Studio-3/Space-Rescue/assets/104808214/6771ce27-6137-4d8e-be47-00046af1e348)
![image](https://github.com/BIT-Studio-3/Space-Rescue/assets/104808214/490084f2-a7a8-43c3-b205-2e37f8be42f3)

**Comment by erokasyuart** [comment]
I like concept 2 the best, but I would prefer the options to be at the bottom of the screen with the restart being slightly larger to encourage the player to keep playing, and I would also probably swap the winning status and the score around so the status is a focal point- the most important information the player needs, and the score can be at the top. Would you be able to make a new concept like this so I can make sure my description was well-spoken and that it doesn't just look better in my head? Thanks.

I also have an idea for when we add different species but I'll save that idea for a different time!

**Comment by erokasyuart** [comment]
I like it... maybe instead of you won/lost, it could use immersive language like mission success/mission failed!

**Comment by ChaseBENNC9** [comment]
> I like it... maybe instead of you won/lost, it could use immersive language like mission success/mission failed!

I had a similar idea. Thanks

**Comment by PBWiseman** [comment]
Agree with Erika. I like the look of the second version one. I think once we have unique animals we should have some sort of an "expanded info" section where it details everything. But that can be added later
