### ISSUE TITLE
Main HUD

### ISSUE THREAD

**Issue by ChaseBENNC9** [BIT-Studio-3/Space-Rescue#135]
As a player, I would like the main HUD of the game to have more integrated visuals, to increase my immersion

This is a continuation of the Planet HUD introduced in the previous sprint. The main objective is to integrate the current Display into something that feels more natural to the space exploration context of the game.
This will rework existing HUD features such as the side planet display and the arrow to match the context of the game - having these items look like they are part of a ship display. and also reworking the warnings when a planet or player gets to close to the black hole

**Comment by PBWiseman** [comment]
Closing this as done. Will add new branches if there are more things we want to add.
