### ISSUE TITLE
Planet score visuals

### ISSUE THREAD

**Issue by PBWiseman** [BIT-Studio-3/Space-Rescue#148]
**User Story**
As someone who likes to play games well, I want to know how well I am doing, so I can keep getting a better score

**Description**
The current score and held animals displays are only temporary and need to be improved to something more natural looking

**Comment by erokasyuart** [comment]
As a player, I want the GUI to look similar to other GUI throughout the game so it stays consistent.
As a player, I'd like to keep track of my animals caught so I can clearly and always know my score.
As a player, I want time pressure while I'm on the planet so I can have a challenge.
